### PR TITLE
Adds HighlightComponent, part of #3795

### PR DESCRIPTION
**Pull request by christinach**
part of https://github.com/pulibrary/orangelight/issues/3795

### CODE REVIEW

**Comment by christinach** [comment]
Setting `<str name="hl.fl">author_display,title_display,title_vern_display</str>`, I would expect not to include `description_t` in the highlighting section.  I'm not sure yet why it lists `description_t`.
```
"highlighting":{
    "9974894583506421":{
      "title_display":["Pregnancy among <em>black</em> <em>teenagers</em> [electronic resource] : hearing before the Subcommittee on Public"]},
    "99126857188706421":{
      "title_display":["The lives of <em>Black</em> and Latino <em>teenagers</em> in a low-income : examining methodological issues when"]},
    "99125180939206421":{
      "title_display":["The lives of <em>Black</em> and Latino <em>teenagers</em> in a low-income : examining methodological issues when"]},
    "99129071662406421":{
      "title_display":["Pregnancy among <em>black</em> <em>teenagers</em> : hearing before the Subcommittee on Public Assistance and"]},
    "99125476820706421":{
      "title_display":["<em>Black</em> youth aspirations : imagined futures and transitions into adulthood / by Botshabelo Maja"]},
    "99127972072106421":{
      "title_display":["Dancing <em>Black</em>, dancing White : rock 'n' roll, race, and youth culture of the 1950s and early 1960s"]},
    "99125315781206421":{
      "description_t":["1 online resource: illustrations (<em>black</em> and white);"],
      "title_display":["Birth Cohort and the <em>Black</em>-White Achievement Gap: The Roles of Access and Health Soon After Birth"]},
    "99109623506421":{
      "title_display":["Runnin' down some lines : the language and culture of <em>Black</em> <em>teenagers</em> / Edith A. Folb."]},
    "99120646253506421":{},
    "9942872243506421":{}}}
```

**Comment by christinach** [comment]
It would be better to have a separate handler for highlighting. Similar to what we did in advanced search.

**Comment by christinach** [comment]
Update: After I destroyed lando and ran the servers again I was able to see in the solr response only the fields I set in the solrconfig.xml as I was expected to. 
```
"highlighting":{
    "9974894583506421":{
      "author_display":[],
      "title_display":["Pregnancy among <em>black</em> <em>teenagers</em> [electronic resource] : hearing before the Subcommittee on Public Assistance and Unemployment Compensation of the Committee on Ways and Means, House of Representatives, Ninety-ninth Congress, second session, February 18, 1986."],
      "title_vern_display":[]},
    "99126857188706421":{
      "author_display":[],
      "title_display":["The lives of <em>Black</em> and Latino <em>teenagers</em> in a low-income : examining methodological issues when conducting a neighborhood ethnography / Randall Clemens."],
      "title_vern_display":[]},
    "99129071662406421":{
      "author_display":[],
      "title_display":["Pregnancy among <em>black</em> <em>teenagers</em> : hearing before the Subcommittee on Public Assistance and Unemployment Compensation of the Committee on Ways and Means, House of Representatives, Ninety-ninth Congress, second session, February 18, 1986. [1986]"],
      "title_vern_display":[]},
    "99125476820706421":{
      "author_display":[],
      "title_display":[],
      "title_vern_display":[]},
    "99127972072106421":{
      "author_display":[],
      "title_display":[],
      "title_vern_display":[]},
    "99125315781206421":{
      "author_display":[],
      "title_display":[],
      "title_vern_display":[]},
    "99109623506421":{
      "author_display":[],
      "title_display":["Runnin' down some lines : the language and culture of <em>Black</em> <em>teenagers</em> / Edith A. "],
      "title_vern_display":[]},
    "99120646253506421":{
      "author_display":[],
      "title_display":[],
      "title_vern_display":[]},
    "9942872243506421":{
      "author_display":[],
      "title_display":[],
      "title_vern_display":[]},
    "99126846939806421":{
      "author_display":[],
      "title_display":[],
      "title_vern_display":[]}}}
```

**Comment by christinach** [comment]
With @rladdusaw @regineheberlein @VickieKarasic @kevinreiss we looked into adding a new `<requestHandler name="search" class="solr.SearchHandler" default="false">` or with no default at all. Solr doesn't like the idea and will trigger a bad request. We looked into adding a requestHandler with a name pointing to a differnet url similar to /advanced search but this adds more complexity as we would have to remap all the solr search configuration. We decided for now to use the existing handler which is in production and specify there the fields we plan to higlight see: [hl.fl](https://github.com/pulibrary/pul_solr/pull/374/files#diff-0659463048550ce849e4a31385608a450aadd735630790044127b17518b7002fR365). We dont expect to have any performance issues even if we dont activate the feature in orangelight; Solr creates the higlight section on the fly only for the results that are on the page.

**Comment by christinach** [comment]
will add a test and then open for review

**Review by sandbergja — APPROVED** [review]
🐬

**Pull request merged**
