### PR TITLE
Rename solr1 capistrano config to production

### LINKED ISSUE #134: change capistrano to deploy production
currently you have to do cap solr1 deploy but we should make it cap production deploy

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #134

### CODE REVIEW

**Comment by tampakis** [comment]
Can you remove solr2.rb and solr3.rb and include those servers in the production deploy?

**Comment by eliotjordan** [comment]
@tampakis Removing those servers is fine, but we only want to interact/deploy to one server. We don't want to add them to the production config.

**Comment by eliotjordan** [comment]
Updated to remove solr2 and solr3 configs.

**Comment by eliotjordan** [comment]
Updated.

**Pull request merged**
