### PR TITLE
Add BackupManager and rake task to run collection backups

### PR DESCRIPTION
**Pull request by hackartisan**
required refactoring some configuration out of capistrano
refs #215

Doesn't close that issue yet; still need to provision the prod solr box with ruby

### CODE REVIEW

**Comment by hackartisan** [comment]
Current status of this PR:
It's deploying and running on the box, now that pulibrary/princeton_ansible#1945 has been addressed

It's getting a timeout, and the backup files appear to have size 0:
```
rake aborted!
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
/solr/pul_solr/releases/20201215151334/lib/pul_solr/backup_manager.rb:32:in `block in backup'
/solr/pul_solr/releases/20201215151334/lib/pul_solr/backup_manager.rb:29:in `each'
/solr/pul_solr/releases/20201215151334/lib/pul_solr/backup_manager.rb:29:in `backup'
/solr/pul_solr/releases/20201215151334/lib/tasks/pul_solr.rake:27:in `block (3 levels) in <top (required)>'
/solr/pul_solr/shared/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => pul_solr:solr8:backup
(See full trace by running task with --trace)
Deleting old backups
Backing up collections: ["catalog-alma-qa", "catalog-staging", "reserves", "dss-staging", "pulfalight-staging", "cicognara-staging"]
deploy@lib-solr-staging4:~$ ls -la /mnt/solr_backup/staging/20201215/
total 0
drwxr-xr-x 2 deploy root 0 Dec 15 15:15 .
drwxr-xr-x 2 deploy root 0 Dec 15 15:10 ..
drwxr-xr-x 2 deploy root 0 Dec 15 15:15 catalog-alma-qa-20201215.bk
drwxr-xr-x 2 deploy root 0 Dec 15 15:15 catalog-staging-20201215.bk
```

It needs to be rebased / the list of collections needs to be updated based on recent changes, migrations.

**Comment by hackartisan** [comment]
This ran correctly on staging.

The backups don't have size 0, they just have weird directory names (with a `.bk`)!

It's bee rebased to pick up newly-created collections.

Ready for review.

**Comment by hackartisan** [comment]
Backups are now running successfully on staging with the use of the `async` flag. Please review but don't merge; production box needs to be re-provisioned before merge / deploy to prod.

**Review by tpendragon — APPROVED** [review]

**Comment by hackartisan** [comment]
@tpendragon would you review again? I have made a few changes. It's ready to merge if 👍🏻

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
