### PR TITLE
improve isbn, issn, lccn search

### PR DESCRIPTION
**Pull request by tampakis**
Closes pulibrary/orangelight#286
Thanks @billdueber!

### CODE REVIEW

**Comment by billdueber** [comment]
You might also consider the filters I made that do similar things on the solr side:

* ISBNs get normalized and (if necessary) expanded from 10-char to 13-digits
* LCCNs get normalized

The nice thing about doing it in solr is that you get it exactly the same at index and query time 

https://github.com/mlibrary/umich_solr_library_filters

**Comment by tampakis** [comment]
Yes we are using the ISBN/LCCN Solr filters at query time. The only reason why I didn't put them in at index time is because it seems like some of the ISBNs that we have aren't considered valid by the normalizer. For instance 9791032000373 becomes a blank string. The ISBN values get normalized before being indexed anyway via the Ruby code from https://github.com/billdueber/library_stdnums.

**Comment by billdueber** [comment]
Hmmm. That's...not right.  I'll look into it. Thanks!

On Mon, Apr 25, 2016 at 1:19 PM, Nikitas Tampakis <notifications@github.com>
wrote:

> Yes we are using the ISBN/LCCN Solr filters at query time. The only reason
> why I didn't put them in at index time is because it seems like some of the
> ISBNs that we have aren't considered valid by the normalizer. For instance
> 9791032000373 becomes a blank string. The ISBN values get normalized before
> being indexed anyway via the Ruby code from
> https://github.com/billdueber/library_stdnums.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pulibrary/pul_solr/pull/3#issuecomment-214448080>
>



-- 
Bill Dueber
Library Systems Programmer
University of Michigan Library

**Comment by billdueber** [comment]
@tampakis My code wasn't dealing with those fancy new 979 ISBNs. Fixed, test added, testing on my local solr. If you find more bugs, please drop me a line!

**Pull request merged**
