### PR TITLE
Use Stanford's CJK Matching

### PR DESCRIPTION
**Pull request by tpendragon**
Fixes bug report from Martin regarding CJK matching without re-enabling
bigrams.

Will require a reindex.

### CODE REVIEW

**Comment by tpendragon** [comment]
If we create the reindex collection with the staging config set and then change the staging configset later for some other feature, won't it effect production when we don't want it to?

I could split index/query here and have query be the old config for prod?

**Comment by hackmastera** [comment]
Hm, I had thought you could update the collection to use a different configset after it had been created, but it looks like that's not true.

Splitting index / query seems like it will help. New stuff will be wonky while the new index is running, but most things will not change.

**Comment by tpendragon** [comment]
The only downside is it'll make testing in staging hard. We won't know if it worked until we make it happen for query-time too.

**Comment by hackmastera** [comment]
We decided to introduce these changes in a new configset for production use, called `catalog-production-alt`. This will allow us to swap between production configsets whenever we need to reindex due to schema changes. It's been documented in the orangelight indexing doc.

**Pull request merged**
