### PR TITLE
Adding a config file for the new library-staging stand alone solr server

### PR DESCRIPTION
**Pull request by carolyncole**

### CODE REVIEW

**Comment by tampakis** [comment]
Hi @carolyncole, I think we may want to consider [reloading the cores](https://github.com/pulibrary/pul_solr/commit/3b3b42ffd85da11781b176a2e53ae2c9bd7693f9#diff-6dc906be0643182e5bae6aa1506221e6) instead on deploys. Let me know if you'd like to try this approach out together. I tried deploying the library-staging role with this branch but the solr service restart failed.

**Comment by carolyncole** [comment]
@tampakis I'd be happy to make a change.  Although I believe I just need to rerun the library-staging playbook in ansible to get the restart to work.  I had just run in on library-prod.

**Comment by carolyncole** [comment]
@tampakis If you want to try and rerun it now.  I ran the ansible update to allow deploy the ability to restart solr.  If reloading the cores would be better we can do that too.

**Comment by tampakis** [comment]
Works great, I'm +1 with this approach. I think if we ever run into situations in the future where it takes a long time to restart solr we might prefer to reload the cores instead.

**Pull request merged**
